### ISSUE TITLE
All posts are HIDDEN and no option for PUBLIC

### ISSUE THREAD

**Issue by Eyewais** [kaimallea/node-imgur#216]
I cannot find any option to post images as public/to community.
If i am missing something please let me know but there is no privacy option to set so that posts are public. 

```
const response = await client.upload({
        image: imgPath,
        title: memeHeading,
        description: 'Dank Meme',
        **_privacy: 'Public'_**
      });
      console.log('I Imgur at:' +Date.now());
      imgurPosted = true;
```

**Comment by KenEucker** [comment]
@Eyewais sorry that you haven't had a reply to this. 

I think the missing piece here for you is that albums are inherently not-public while galleries are public posts shared to the community. Maybe creating a gallery instead of an album is what you are looking for?

It must be that the default upload is to attach the image to an album? I will have to look into that.

At any rate, this package is now being maintained in another repository: https://github.com/KenEucker/imgur

imgur@v2 will be released before the end of 2021, and with that will come a couple of breaking changes -> dropping support for filesystem uploads means you have to create your streams on your own and pass them to the API.

Please come help us maintain v2!
